[package]
name = "ast-toolkit"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
description = "A collection of structs and interfaces extremely useful when working with compilers that parse text into ASTs."

repository = "https://github.com/Lut99/ast-toolkit-rs"


[dependencies]
console = "0.15"
enum-debug = { git = "https://github.com/Lut99/enum-debug", features = ["derive"] }
never-say-never = "6.6.666"
num-traits = "0.2"
unicode-segmentation = "1.10"

ast-toolkit-derive = { path = "../ast-toolkit-derive", optional = true }


[features]
default = [ "derive" ]
derive = [ "dep:ast-toolkit-derive" ]
